-- ============================================================
-- BRISANJE SAMPLE PODATAKA - obrnut redosled od INSERT-ova
-- ============================================================

-- Vezne tabele i deca prvo
DELETE FROM CITIRA;
DELETE FROM POVEZAN_SA;
DELETE FROM VRSI_RECENZIJU;
DELETE FROM RUNDA_RECENZIJE;

DELETE FROM FAJLOVI;
DELETE FROM VERZIJA;

DELETE FROM AUTORSTVO;
DELETE FROM PUBLIKACIJA_KLJUCNE_RECI;

-- Podtipovi publikacije
DELETE FROM SA_PODRZANE_PLATFORME;
DELETE FROM SOFTVERSKI_ARTEFAKT;
DELETE FROM DATASET;
DELETE FROM DOKTORSKA_DISERTACIJA;
DELETE FROM PREZENTACIJA;
DELETE FROM OBRAZOVNI_MATERIJAL;
DELETE FROM TEHNICKI_IZVESTAJ;
DELETE FROM POGLAVLJE_UREDNICI;
DELETE FROM POGLAVLJE_U_KNJIZI;
DELETE FROM KNJIGA_UREDNICI;
DELETE FROM KNJIGA;
DELETE FROM NAUCNI_RAD;

-- Izvori
DELETE FROM CASOPIS;
DELETE FROM KONFERENCIJA;
DELETE FROM IZVOR;

-- Publikacija
DELETE FROM PUBLIKACIJA;

-- Istrazivac visevrednosni atributi
DELETE FROM ISTRAZIVAC_EMAIL;
DELETE FROM ISTRAZIVAC_TELEFONI;

-- Angazovanje (veza institucija-istrazivac)
DELETE FROM ANGAZOVANJE;

-- Institucija visevrednosni atributi
DELETE FROM INSTITUCIJA_NAUCNE_OBLASTI;
DELETE FROM INSTITUCIJA_KONTAKT_TEL;
DELETE FROM INSTITUCIJA_KONTAKT_MAIL;

-- Korenski entiteti
DELETE FROM ISTRAZIVAC;
DELETE FROM INSTITUCIJA;

-- Resetovanje sekvenci
ALTER SEQUENCE SEQ_INSTITUCIJA RESTART START WITH 1;
ALTER SEQUENCE SEQ_ISTRAZIVAC RESTART START WITH 1;
ALTER SEQUENCE SEQ_PUBLIKACIJA RESTART START WITH 1;
ALTER SEQUENCE SEQ_IZVOR RESTART START WITH 1;
ALTER SEQUENCE seq_verzija RESTART START WITH 1;
ALTER SEQUENCE seq_runda_recenzije RESTART START WITH 1;
ALTER SEQUENCE seq_inst_mail RESTART START WITH 1;
ALTER SEQUENCE seq_inst_tel RESTART START WITH 1;
ALTER SEQUENCE seq_inst_oblast RESTART START WITH 1;
ALTER SEQUENCE seq_istr_tel RESTART START WITH 1;
ALTER SEQUENCE seq_istr_email RESTART START WITH 1;
ALTER SEQUENCE seq_pub_rec RESTART START WITH 1;
ALTER SEQUENCE seq_sa_platforma RESTART START WITH 1;
ALTER SEQUENCE seq_fajlovi RESTART START WITH 1;
ALTER SEQUENCE seq_knjiga_urednik RESTART START WITH 1;
ALTER SEQUENCE seq_poglavlje_urednik RESTART START WITH 1;

COMMIT;
