global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Reflection;
global using System.Threading.Tasks;
global using System.Text;
global using RepozitorijumLibrary.Entiteti;
global using RepozitorijumLibrary.DTOs;
global using NHibernate;
global using static RepozitorijumLibrary.Extensions;
global using System.Diagnostics.CodeAnalysis;